<?php
class ErrorHandler
{

    const INVALID_REFERECE_ID_TYPE = "INVALID REFERECE ID TYPE";
    const UNABLE_TO_CREATE_REFERECE_ID = "UNABLE TO CREATE REFERENCE ID";
    const UNKNOWN_ERROR = "UNKNOWN ERROR";
}
